### ISSUE TITLE
Code was not spartanized. 

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5777/SmartCity-ParkingManagement#119]
I spartanized it for you. Shame...

**Comment by yossigil** [comment]
@TomPalny @idabran @orimarco @yh-github @AdiOmari

**Comment by tomnof** [comment]
Since we did spartanized the code during the work, it was a surprise to see you did it for us..
We viewed the changes and:
1. Most of them are $ and cents which we agreed not to use
2. The rest - after checking with the other team members, Spartan did not suggest these changes. We checked for a new version, and found out that there was a version update we missed during the semester. Just to make sure – it does doesn’t update automatically? We need to do it manually?
Please note that although we did miss the version update, our code was spartanized nicely according to the last version.

**Comment by tomnof** [comment]
all should update the spartan version. Please check your checkbox when updated.
- [x] Inbal
- [x] Dani
- [x] Or
- [x] Assaf
- [x] Tom

https://marketplace.eclipse.org/content/spartan-refactoring-0

**Comment by matityahuinba** [comment]
Done! :v:

**Comment by ortroyaner** [comment]
👍

**Comment by dshames** [comment]
👍

**Comment by yossigil** [comment]
👍
