### ISSUE TITLE
Separate the system to modules 

### ISSUE THREAD

**Issue by tomnof** [TechnionYP5777/SmartCity-ParkingManagement#133]
Change the architecture of the system - Logic, DB , GUI.
Time estimation : 20-25 hours

**Comment by matityahuinba** [comment]
This issue is divided into several steps and multiple tasks. 
The initial tasks are in the following issues:
https://github.com/TechnionYP5777/SmartCity-ParkingManagement/issues/142
https://github.com/TechnionYP5777/SmartCity-ParkingManagement/issues/143
https://github.com/TechnionYP5777/SmartCity-ParkingManagement/issues/144
https://github.com/TechnionYP5777/SmartCity-ParkingManagement/issues/145
Each issue will show its progress.
