### ISSUE TITLE
Create "Install Me" Wiki page

### ISSUE THREAD

**Issue by matityahuinba** [TechnionYP5777/SmartCity-ParkingManagement#139]
Create "Install Me" Wiki page according to Yossi’s demands on Telegram:
Includes:
- which "mvn build"s should be done

-  installation procedure

- operation

- eclipse instructions

-  web instructions

- Any other necessary explanations

**Comment by assaflu** [comment]
@matityahuinba  can you review the wikipage I added and give your oppinion

**Comment by matityahuinba** [comment]
Looking good!
1. maybe we'll add few screenshots to simplify the process?
2. any reference to install mvn?
3. few typo mistakes - 
Ecxisting --> Existing
Runnig --> Running
New make sure --> Now make sure?

:smiley:

**Comment by yossigil** [comment]
Good job Inbal

**Comment by tanyabrokhman** [comment]
I think this time it's "good job Assaf" :)

On Mar 31, 2017 20:20, "Yossi Gil" <notifications@github.com> wrote:

Good job Inbal

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/TechnionYP5777/SmartCity-ParkingManagement/issues/139#issuecomment-290774368>,
or mute the thread
