### ISSUE TITLE
[Final] Bug in order

### ISSUE THREAD

**Issue by SlasherTech** [TechnionYP5777/SmartCity-ParkingManagement#190]
I chose legal params and it told me the time is not legal ( but it is)

**Comment by SlasherTech** [comment]
![bugtime](https://user-images.githubusercontent.com/23153329/27768963-a58e7e14-5f28-11e7-8aba-6837591f0737.jpg)

**Comment by dshames** [comment]
Is there a chance you're confusing between AM and PM?
Try order the parking from 1115AM to 1215 PM and let us know if its working.

Reminder: you can only order parking slots for the same day in one order (two different days: two different orders, its written in the bugs section in the wiki although its not a bug, its by design).

**Comment by SlasherTech** [comment]
no , i didnt confuse.
you can see it yourself in the picture.

**Comment by dshames** [comment]
**Reminder: you can only order parking slots for the same day in one order (two different days: two different orders, its written in the bugs section in the wiki although its not a bug, its by design).**

you order a parking  from 11:14 AM  (morning) to 12:14 AM (night).  
It means you order a parking for two different days

**Comment by SlasherTech** [comment]
ok , if you say its by design maybe you should consider changing it

**Comment by tomnof** [comment]
This might be nice to have, but it wasn't in our main features list.
