### ISSUE TITLE
ID should not contain only digits

### ISSUE THREAD

**Issue by TomPalny** [TechnionYP5777/SmartCity-ParkingManagement#199]
Any system should not require the government issued personal identification (תעודת זהות) as a requirement, unless it is a bank or hospital. So, you should either allow a non-digit only ID, or make this field optional.

**Comment by matityahuinba** [comment]
We took the Technion portal system as a representative example. There,  ID is based on "student number" only. Here, because the mapping of the parking slots is inside the Technion, we left the ID as a customer ID. Of course, this field can be changed. If necessary, we will change the string length limit and the digits only..
