### ISSUE TITLE
Searching for parking in the past should not be allowed

### ISSUE THREAD

**Issue by TomPalny** [TechnionYP5777/SmartCity-ParkingManagement#200]
Hi, 
Simple check for the "Order Parking slot" procedure: past dates should not be allowed (same for past time in current date) and throw an error. Below a picture of a situation that should not give any results but just a text box "The date you selected already passed".
![image](https://user-images.githubusercontent.com/15875450/27789403-1e2f950c-5ff5-11e7-810b-d0fe086157db.png)

**Comment by matityahuinba** [comment]
please note "Rank parking slot" on the user manual -
![image](https://user-images.githubusercontent.com/15820085/27789723-4815f9e6-5ff6-11e7-8215-9607f467ae5e.png)

Its not a bug, its intentional. In order to rank orders, their date need to pass. So, we allowed the user to order slots on the past, and in their next connection to rank them.
Also written on "Known Bug" (Although again is not a bug :) )

**Comment by TomPalny** [comment]
Got it, thanks

בתודה,
תום
