### ISSUE TITLE
Karma and Todos for Shahar Yair

### ISSUE THREAD

**Issue by zvili** [TechnionYP5777/SmartCity-ParkingManagement#8]
_From @Shahar-Y on October 31, 2016 8:21_

- [x]  Use a picture, photo or distinct avatar. Don''t use an automatic icon:
- [x]  Make sure you present yourself by a readable **nick**
- [x]  Describe yourself in the bio page; FYI, here is my description:
- [x]  State that you are (not) in search for a job, i.e., mark, or unmark this box:

_Copied from original issue: SpartanRefactoring/Spartanizer#665_

**Comment by zvili** [comment]
_From @Shahar-Y on October 31, 2016 8:22_

@YossiGil: Done.

**Comment by zvili** [comment]
_From @yosefraisman on October 31, 2016 8:35_

I feel sorry for whoever's going to invent time travel, because no accomplishment could ever compete with this original and, quite frankly, thought-provoking karma page. It's great.

**Comment by zvili** [comment]
_From @RoeyMaor on October 31, 2016 9:10_

I sincerely think your karma is amazing.
take a quick look at mine: #670

**Comment by zvili** [comment]
_From @EliaTraore on October 31, 2016 15:20_

OMG!!! This is the best karma page EVERRRRR



*Not edited at all

**Comment by Shahar-Y** [comment]
As agreed, I'm posting here the current issues I'm assigned on: #24 , #25 , #26 .
@zahimizrahi and I are both assigned to issue #23, and will decide on who takes care of it in the future. Perhaps we will work on it together. This comment will be updated if changes occur.
My learning javaFX issue is here: #56.

**Comment by orimarco** [comment]
How would you rank your amount of contribution to the project compared to others in the group?
Please specify the ordinal of the **quintile**.

**Comment by Shahar-Y** [comment]
Since each member of the group is working on a different part of the project, the comparison is irrelevant. 
A large portion of the work can't be seen on github since it won't be uploaded to it, like setting up the server and database, or learning how to use javaFX for the gui.
However, I can honestly say that each member of the team is doing a wonderful job, as I have seen in the meeting held yesterday (a meeting summary should be uploaded today).

**Comment by yossigil** [comment]
But, the first six or so issues you did were done by the team toegher. 

![image](https://cloud.githubusercontent.com/assets/12775400/21139624/7d096218-c13c-11e6-8d19-c375005292d5.png)

**Comment by Shahar-Y** [comment]
In the beginning, all members of the group sat together and had several discussions on how we are going to make the project work. These meetings included organizing our thoughts on how the final result of the semester is going to look like and the features it will include, same for the final submission at the end of the year. We also agreed on what needs to be done, who does what,  etc... 
In these meetings, all of the members were involved in most of the meetings and therefore contributed equally. 
After that, we started writing code and setting up the environment- now(generally speaking) every member is working by him/herself on the part they're supposed to do. 
According to the meeting held yesterday, everyone has done a great job with working on the part they are supposed to be working on.

**Comment by Shahar-Y** [comment]
I have now realized that I neglected my karma page, and haven't written here about my work in each week as was suggested in the beginning of the semester. 
Therefore, I've decided to briefly summarize my actions in the project so far. 
@zahimizrahi, @ortroyaner and I were assigned to build the GUI for the project. Zahi and myself took care of the DriverGUI and Or was assigned to take care of the ManagerGui. 
The first week of the work was mainly dedicated to studying JavaFX and experimenting with it, as can be seen under gui.driver.shaharTesting package. Issue #56 describes what I had to learn.
The next step was to build the skeleton of the gui.driver screens, as there was no functionality yet. You can see that in issues #23 , #24 , #25 , #26 I was assigned to.
After that, we integrated the functionality  and improved the looks of the GUI (#83 , #89).
Throughout the progress, I fixed many of the bugs that came up, as can be seen in my commits. 
And I think that pretty much sums it up. I currently have no issues to work on because I finished everything I was supposed to do in this sprint, but if something comes up I'll be the first one to help with it.
