### ISSUE TITLE
Create Parking Areas List sub-screen for the management GUI

### ISSUE THREAD

**Issue by Shahar-Y** [TechnionYP5777/SmartCity-ParkingManagement#94]
As described in issue #93, the first screen of the management's manually edit feature contains the list of areas of which they choose which one they want to change. 
It also has a 'View and Edit' button, leading to the screen described in issue #95.
The issue will be closed when the screen is ready.

**Comment by ortroyaner** [comment]
This sub-screen is integrated in the main manager panel, so we can consider it as done.
@matityahuinba (#93) please pay attention that we will need a function to collect the data (parking areas names) from the server so that we will be able to show them.
The GUI is set and therefore I'm closing the issue.
