### ISSUE TITLE
Create Parking Areas Info sub-screen for the management GUI

### ISSUE THREAD

**Issue by Shahar-Y** [TechnionYP5777/SmartCity-ParkingManagement#95]
As described in issue #93, the second screen of the management's manually edit feature contains the current information about the selected parking slot area(#94) such as sticker color, number of free parking slots, total parking slots, etc.
It also has an 'Update' button leading to the screen in issue #96, and a 'Back' button leading to the screen in issue #94.
The issue will be closed when the screen is ready.

**Comment by ortroyaner** [comment]
This sub-screen is integrated in the main manager screen (#103), so we can consider it as done.
@matityahuinba (#93) please pay attention that we will need a function to collect the data (parking areas info about slots) from the server so that we will be able to show them.
The GUI is set and therefore I'm closing the issue.
